profile_id: 1
profile_label: default
enabled: true
action:
  type: sync
mapping:
  composite_in:
    target:
      location: body
    transform:
      - type: base64
    separator:
      type: delimiter
      value: "+"
  encrypted_data_out:
    target:
      location: body
    transform:
      - type: base64
