profile_id: default
channel_type: http
enabled: true
priority: 100
mapping:
  combined_in:
    target:
      location: body
      key: ""
    transform:
      - type: base64
    separator: "+"
  combined_out:
    target:
      location: body
      key: ""
    transform:
      - type: base64
    separator: "+"
